"""updated application

Revision ID: 63a94d832b2d
Revises: 6467dff2b436
Create Date: 2024-07-10 08:41:43.462400

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63a94d832b2d'
down_revision = '6467dff2b436'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_type',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
