"""Added user relationship to Event model

Revision ID: 6467dff2b436
Revises: dcfdc814399f
Create Date: 2024-07-09 22:48:43.662947

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6467dff2b436'
down_revision = 'dcfdc814399f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_constraint('applications_ibfk_1', type_='foreignkey')
        batch_op.drop_column('event_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('applications_ibfk_1', 'events', ['event_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
